fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        users:
            types:
                user:
                    properties:
                        username: ~
                        firstName: ~
                        lastName: ~
                        email: ~
                    persistence:
                        driver: orm
                        model: App\Entity\User
                        provider: ~
                        finder: ~
        tasks:
            types:
                task:
                    properties:
                        title: ~
                        user: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Task
                        provider: ~
                        finder: ~