security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        db_user:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: _username
                password_parameter: _password
            logout:
                path: logout
                target: login
            user_checker: App\Security\UserChecker
    access_control:
         - { path: '^/([a-z]{2}/)?$', roles: IS_AUTHENTICATED_FULLY }
         - { path: '^/([a-z]{2}/)?login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/([a-z]{2}/)?task/view', roles: [ROLE_ADMIN, ROLE_USER] }
         - { path: '^/([a-z]{2}/)?task/my-tasks', roles: [ROLE_USER] }
         - { path: '^/([a-z]{2}/)?task', roles: ROLE_ADMIN }
         - { path: '^/([a-z]{2}/)?user', roles: ROLE_ADMIN }
