task_index:
    path: task/index
    controller: App\Controller\TaskController::index

task_add:
    path: task/add
    controller: App\Controller\TaskController::add

task_edit:
    path: task/edit/{id}
    controller: App\Controller\TaskController::edit
    requirements:
        id: '\d+'

task_view:
    path: task/view/{id}
    controller: App\Controller\TaskController::view
    requirements:
        id: '\d+'

task_delete:
    path: task/delete/{id}
    controller: App\Controller\TaskController::delete
    methods: [DELETE]

my_tasks:
    path: task/my-tasks
    controller: App\Controller\TaskController::myTasks

task_complete:
    path: task/complete/{id}
    controller: App\Controller\TaskController::complete
    methods: [POST]