user:
  resource: 'routes/user.yml'
  prefix:
      en: '/user'
      es: '/es/user'

task:
  resource: "routes/task.yml"
  prefix:
      en: '/task'
      es: '/es/task'

home:
  resource: "routes/home.yml"
  prefix:
      en: ''
      es: '/es'
