user:
  resource: 'routes/user.yml'
  prefix:
      en: '/'
      es: '/es'

task:
  resource: 'routes/task.yml'
  prefix:
      en: '/'
      es: '/es'

home:
  resource: 'routes/home.yml'
  prefix:
      en: '/'
      es: '/es'
